name: MAIN Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tests:
    uses: kiranvattikuti146/VSTEST-ACTION/.github/workflows/VStest-reusable.yml@main
    with:
      runsOn: ""
      dotnet-version: "7.0.x"
      testSelector: "testAssemblies" # Using testAssemblies as the test selection method
      testAssemblyVer2: '*AspnetCoreMvcFull.dll' # Specify the test files to run
      code-coverage-enabled: true
      configuration: "Release"
      platform: "x64"
      test-run-title: "Unit Tests"
      run-in-parallel: true
      testPlan: "Plan1"
      testSuite: "SuiteA"
      testConfiguration: "DebugConfig"
      tcmTestRun: "1234"
      uiTests: false
      vsTestVersion: "latest"
      diagnosticsEnabled: true
      rerunFailedTests: true
      rerunType: "specific"
      rerunMaxAttempts: "3"
      dontDistribute: false
      searchFolder: "${{ github.workspace }}" # Updated input
      resultsFolder: "${{ github.workspace }}/TestResults" # Updated input
      testFiltercriteria: "" # New input
      runOnlyImpactedTests: false # New input
      runAllTestsAfterXBuilds: "50" # New input
